/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "s3eFacebook.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef s3eFBSession*(*s3eFBInit_t)(const char* appId);
typedef  s3eResult(*s3eFBTerminate_t)(s3eFBSession* session);
typedef  s3eResult(*s3eFBSession_Login_t)(s3eFBSession* session, s3eFBLoginCallbackFn cb, void* cbData, const char** pPermissions, int numPermissions);
typedef  s3eResult(*s3eFBSession_Logout_t)(s3eFBSession* session);
typedef    s3eBool(*s3eFBSession_LoggedIn_t)(s3eFBSession* session);
typedef const char*(*s3eFBSession_AccessToken_t)(s3eFBSession* session);
typedef s3eFBDialog*(*s3eFBDialog_WithAction_t)(s3eFBSession* session, const char* action);
typedef  s3eResult(*s3eFBDialog_Delete_t)(s3eFBDialog* dialog);
typedef  s3eResult(*s3eFBDialog_AddParamString_t)(s3eFBDialog* dialog, const char* name, const char* value);
typedef  s3eResult(*s3eFBDialog_AddParamNumber_t)(s3eFBDialog* dialog, const char* name, int64 value);
typedef  s3eResult(*s3eFBDialog_Show_t)(s3eFBDialog* dialog, s3eFBDialogCallbackFn cb, void* cbData);
typedef    s3eBool(*s3eFBDialog_Error_t)(s3eFBDialog* dialog);
typedef     uint32(*s3eFBDialog_ErrorCode_t)(s3eFBDialog* dialog);
typedef const char*(*s3eFBDialog_ErrorString_t)(s3eFBDialog* dialog);
typedef    s3eBool(*s3eFBDialog_Complete_t)(s3eFBDialog* dialog);
typedef const char*(*s3eFBDialog_DidNotCompleteWithUrl_t)(s3eFBDialog* dialog);
typedef s3eFBRequest*(*s3eFBRequest_WithMethodName_t)(s3eFBSession* session, const char* methodName, const char* httpMethod);
typedef s3eFBRequest*(*s3eFBRequest_WithGraphPath_t)(s3eFBSession* session, const char* graphPath, const char* httpMethod);
typedef  s3eResult(*s3eFBRequest_Delete_t)(s3eFBRequest* request);
typedef  s3eResult(*s3eFBRequest_AddParamString_t)(s3eFBRequest* request, const char* name, const char* value);
typedef  s3eResult(*s3eFBRequest_AddParamNumber_t)(s3eFBRequest* request, const char* name, int64 value);
typedef  s3eResult(*s3eFBRequest_Send_t)(s3eFBRequest* request, s3eFBRequestCallbackFn cb, void* cbData);
typedef    s3eBool(*s3eFBRequest_Error_t)(s3eFBRequest* request);
typedef     uint32(*s3eFBRequest_ErrorCode_t)(s3eFBRequest* request);
typedef const char*(*s3eFBRequest_ErrorString_t)(s3eFBRequest* request);
typedef    s3eBool(*s3eFBRequest_Complete_t)(s3eFBRequest* request);
typedef s3eFBResponseType(*s3eFBRequest_ResponseType_t)(s3eFBRequest* request);
typedef const char*(*s3eFBRequest_ResponseRaw_t)(s3eFBRequest* request);
typedef const char*(*s3eFBRequest_ResponseAsString_t)(s3eFBRequest* request);
typedef      int64(*s3eFBRequest_ResponseAsNumber_t)(s3eFBRequest* request);
typedef        int(*s3eFBRequest_ResponseArrayCount_t)(s3eFBRequest* request);
typedef const char*(*s3eFBRequest_ResponseArrayItemAsString_t)(s3eFBRequest* request, int index);
typedef    s3eBool(*s3eFBRequest_ResponseDictionaryContainsItem_t)(s3eFBRequest* request, const char* key);
typedef const char*(*s3eFBRequest_ResponseDictionaryItemAsString_t)(s3eFBRequest* request, const char* key);
typedef s3eFBRequest*(*s3eFBRequest_WithURL_t)(s3eFBSession* session, const char* url, const char* httpMethod);

/**
 * struct that gets filled in by s3eFacebookRegister
 */
typedef struct s3eFacebookFuncs
{
    s3eFBInit_t m_s3eFBInit;
    s3eFBTerminate_t m_s3eFBTerminate;
    s3eFBSession_Login_t m_s3eFBSession_Login;
    s3eFBSession_Logout_t m_s3eFBSession_Logout;
    s3eFBSession_LoggedIn_t m_s3eFBSession_LoggedIn;
    s3eFBSession_AccessToken_t m_s3eFBSession_AccessToken;
    s3eFBDialog_WithAction_t m_s3eFBDialog_WithAction;
    s3eFBDialog_Delete_t m_s3eFBDialog_Delete;
    s3eFBDialog_AddParamString_t m_s3eFBDialog_AddParamString;
    s3eFBDialog_AddParamNumber_t m_s3eFBDialog_AddParamNumber;
    s3eFBDialog_Show_t m_s3eFBDialog_Show;
    s3eFBDialog_Error_t m_s3eFBDialog_Error;
    s3eFBDialog_ErrorCode_t m_s3eFBDialog_ErrorCode;
    s3eFBDialog_ErrorString_t m_s3eFBDialog_ErrorString;
    s3eFBDialog_Complete_t m_s3eFBDialog_Complete;
    s3eFBDialog_DidNotCompleteWithUrl_t m_s3eFBDialog_DidNotCompleteWithUrl;
    s3eFBRequest_WithMethodName_t m_s3eFBRequest_WithMethodName;
    s3eFBRequest_WithGraphPath_t m_s3eFBRequest_WithGraphPath;
    s3eFBRequest_Delete_t m_s3eFBRequest_Delete;
    s3eFBRequest_AddParamString_t m_s3eFBRequest_AddParamString;
    s3eFBRequest_AddParamNumber_t m_s3eFBRequest_AddParamNumber;
    s3eFBRequest_Send_t m_s3eFBRequest_Send;
    s3eFBRequest_Error_t m_s3eFBRequest_Error;
    s3eFBRequest_ErrorCode_t m_s3eFBRequest_ErrorCode;
    s3eFBRequest_ErrorString_t m_s3eFBRequest_ErrorString;
    s3eFBRequest_Complete_t m_s3eFBRequest_Complete;
    s3eFBRequest_ResponseType_t m_s3eFBRequest_ResponseType;
    s3eFBRequest_ResponseRaw_t m_s3eFBRequest_ResponseRaw;
    s3eFBRequest_ResponseAsString_t m_s3eFBRequest_ResponseAsString;
    s3eFBRequest_ResponseAsNumber_t m_s3eFBRequest_ResponseAsNumber;
    s3eFBRequest_ResponseArrayCount_t m_s3eFBRequest_ResponseArrayCount;
    s3eFBRequest_ResponseArrayItemAsString_t m_s3eFBRequest_ResponseArrayItemAsString;
    s3eFBRequest_ResponseDictionaryContainsItem_t m_s3eFBRequest_ResponseDictionaryContainsItem;
    s3eFBRequest_ResponseDictionaryItemAsString_t m_s3eFBRequest_ResponseDictionaryItemAsString;
    s3eFBRequest_WithURL_t m_s3eFBRequest_WithURL;
} s3eFacebookFuncs;

static s3eFacebookFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xd2988f0a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: s3eFacebook");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xd2988f0a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eFacebookAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eBool s3eExtFacebookAvailable()
{
    return s3eFacebookAvailable();
}

s3eFBSession* s3eFBInit(const char* appId)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[0] func: s3eFBInit"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBInit(appId);
}

s3eResult s3eFBTerminate(s3eFBSession* session)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[1] func: s3eFBTerminate"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBTerminate(session);
}

s3eResult s3eFBSession_Login(s3eFBSession* session, s3eFBLoginCallbackFn cb, void* cbData, const char** pPermissions, int numPermissions)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[2] func: s3eFBSession_Login"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBSession_Login(session, cb, cbData, pPermissions, numPermissions);
}

s3eResult s3eFBSession_Logout(s3eFBSession* session)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[3] func: s3eFBSession_Logout"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBSession_Logout(session);
}

s3eBool s3eFBSession_LoggedIn(s3eFBSession* session)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[4] func: s3eFBSession_LoggedIn"));

    if (!_extLoad())
        return S3E_FALSE;

    return g_Ext.m_s3eFBSession_LoggedIn(session);
}

const char* s3eFBSession_AccessToken(s3eFBSession* session)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[5] func: s3eFBSession_AccessToken"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBSession_AccessToken(session);
}

s3eFBDialog* s3eFBDialog_WithAction(s3eFBSession* session, const char* action)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[6] func: s3eFBDialog_WithAction"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBDialog_WithAction(session, action);
}

s3eResult s3eFBDialog_Delete(s3eFBDialog* dialog)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[7] func: s3eFBDialog_Delete"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBDialog_Delete(dialog);
}

s3eResult s3eFBDialog_AddParamString(s3eFBDialog* dialog, const char* name, const char* value)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[8] func: s3eFBDialog_AddParamString"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBDialog_AddParamString(dialog, name, value);
}

s3eResult s3eFBDialog_AddParamNumber(s3eFBDialog* dialog, const char* name, int64 value)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[9] func: s3eFBDialog_AddParamNumber"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBDialog_AddParamNumber(dialog, name, value);
}

s3eResult s3eFBDialog_Show(s3eFBDialog* dialog, s3eFBDialogCallbackFn cb, void* cbData)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[10] func: s3eFBDialog_Show"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBDialog_Show(dialog, cb, cbData);
}

s3eBool s3eFBDialog_Error(s3eFBDialog* dialog)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[11] func: s3eFBDialog_Error"));

    if (!_extLoad())
        return S3E_FALSE;

    return g_Ext.m_s3eFBDialog_Error(dialog);
}

uint32 s3eFBDialog_ErrorCode(s3eFBDialog* dialog)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[12] func: s3eFBDialog_ErrorCode"));

    if (!_extLoad())
        return 0;

    return g_Ext.m_s3eFBDialog_ErrorCode(dialog);
}

const char* s3eFBDialog_ErrorString(s3eFBDialog* dialog)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[13] func: s3eFBDialog_ErrorString"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBDialog_ErrorString(dialog);
}

s3eBool s3eFBDialog_Complete(s3eFBDialog* dialog)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[14] func: s3eFBDialog_Complete"));

    if (!_extLoad())
        return S3E_FALSE;

    return g_Ext.m_s3eFBDialog_Complete(dialog);
}

const char* s3eFBDialog_DidNotCompleteWithUrl(s3eFBDialog* dialog)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[15] func: s3eFBDialog_DidNotCompleteWithUrl"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBDialog_DidNotCompleteWithUrl(dialog);
}

s3eFBRequest* s3eFBRequest_WithMethodName(s3eFBSession* session, const char* methodName, const char* httpMethod)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[16] func: s3eFBRequest_WithMethodName"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBRequest_WithMethodName(session, methodName, httpMethod);
}

s3eFBRequest* s3eFBRequest_WithGraphPath(s3eFBSession* session, const char* graphPath, const char* httpMethod)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[17] func: s3eFBRequest_WithGraphPath"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBRequest_WithGraphPath(session, graphPath, httpMethod);
}

s3eResult s3eFBRequest_Delete(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[18] func: s3eFBRequest_Delete"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBRequest_Delete(request);
}

s3eResult s3eFBRequest_AddParamString(s3eFBRequest* request, const char* name, const char* value)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[19] func: s3eFBRequest_AddParamString"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBRequest_AddParamString(request, name, value);
}

s3eResult s3eFBRequest_AddParamNumber(s3eFBRequest* request, const char* name, int64 value)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[20] func: s3eFBRequest_AddParamNumber"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBRequest_AddParamNumber(request, name, value);
}

s3eResult s3eFBRequest_Send(s3eFBRequest* request, s3eFBRequestCallbackFn cb, void* cbData)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[21] func: s3eFBRequest_Send"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eFBRequest_Send(request, cb, cbData);
}

s3eBool s3eFBRequest_Error(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[22] func: s3eFBRequest_Error"));

    if (!_extLoad())
        return S3E_FALSE;

    return g_Ext.m_s3eFBRequest_Error(request);
}

uint32 s3eFBRequest_ErrorCode(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[23] func: s3eFBRequest_ErrorCode"));

    if (!_extLoad())
        return 0;

    return g_Ext.m_s3eFBRequest_ErrorCode(request);
}

const char* s3eFBRequest_ErrorString(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[24] func: s3eFBRequest_ErrorString"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBRequest_ErrorString(request);
}

s3eBool s3eFBRequest_Complete(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[25] func: s3eFBRequest_Complete"));

    if (!_extLoad())
        return S3E_FALSE;

    return g_Ext.m_s3eFBRequest_Complete(request);
}

s3eFBResponseType s3eFBRequest_ResponseType(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[26] func: s3eFBRequest_ResponseType"));

    if (!_extLoad())
        return UNKNOWN;

    return g_Ext.m_s3eFBRequest_ResponseType(request);
}

const char* s3eFBRequest_ResponseRaw(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[27] func: s3eFBRequest_ResponseRaw"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBRequest_ResponseRaw(request);
}

const char* s3eFBRequest_ResponseAsString(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[28] func: s3eFBRequest_ResponseAsString"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBRequest_ResponseAsString(request);
}

int64 s3eFBRequest_ResponseAsNumber(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[29] func: s3eFBRequest_ResponseAsNumber"));

    if (!_extLoad())
        return 0;

    return g_Ext.m_s3eFBRequest_ResponseAsNumber(request);
}

int s3eFBRequest_ResponseArrayCount(s3eFBRequest* request)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[30] func: s3eFBRequest_ResponseArrayCount"));

    if (!_extLoad())
        return 0;

    return g_Ext.m_s3eFBRequest_ResponseArrayCount(request);
}

const char* s3eFBRequest_ResponseArrayItemAsString(s3eFBRequest* request, int index)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[31] func: s3eFBRequest_ResponseArrayItemAsString"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBRequest_ResponseArrayItemAsString(request, index);
}

s3eBool s3eFBRequest_ResponseDictionaryContainsItem(s3eFBRequest* request, const char* key)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[32] func: s3eFBRequest_ResponseDictionaryContainsItem"));

    if (!_extLoad())
        return S3E_FALSE;

    return g_Ext.m_s3eFBRequest_ResponseDictionaryContainsItem(request, key);
}

const char* s3eFBRequest_ResponseDictionaryItemAsString(s3eFBRequest* request, const char* key)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[33] func: s3eFBRequest_ResponseDictionaryItemAsString"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBRequest_ResponseDictionaryItemAsString(request, key);
}

s3eFBRequest* s3eFBRequest_WithURL(s3eFBSession* session, const char* url, const char* httpMethod)
{
    IwTrace(FACEBOOK_VERBOSE, ("calling s3eFacebook[34] func: s3eFBRequest_WithURL"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eFBRequest_WithURL(session, url, httpMethod);
}
